// File generated by Firebase CLI and agent for codeara-apps.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0uQv3k9klzzBebKCQzuO1sjnNze1MAu8',
    appId: '1:559959767324:web:50b7434a60cba6b5afe2d9',
    messagingSenderId: '559959767324',
    projectId: 'codeara-apps',
    authDomain: 'codeara-apps.firebaseapp.com',
    storageBucket: 'codeara-apps.firebasestorage.app',
    measurementId: 'G-BGVYVS3RLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9T2Zyc9Dit9Yds7RTGhnau57T4vm11c',
    appId: '1:559959767324:android:e7498347eec8a21eafe2d9',
    messagingSenderId: '559959767324',
    projectId: 'codeara-apps',
    storageBucket: 'codeara-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk9T2Zyc9Dit9Yds7RTGhnau57T4vm11c',
    appId: '1:559959767324:ios:e7498347eec8a21eafe2d9',
    messagingSenderId: '559959767324',
    projectId: 'codeara-apps',
    storageBucket: 'codeara-apps.firebasestorage.app',
    iosBundleId: 'com.codeara.snakeara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk9T2Zyc9Dit9Yds7RTGhnau57T4vm11c',
    appId: '1:559959767324:ios:e7498347eec8a21eafe2d9',
    messagingSenderId: '559959767324',
    projectId: 'codeara-apps',
    storageBucket: 'codeara-apps.firebasestorage.app',
    iosBundleId: 'com.codeara.snakeara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0uQv3k9klzzBebKCQzuO1sjnNze1MAu8',
    appId: '1:559959767324:web:50b7434a60cba6b5afe2d9',
    messagingSenderId: '559959767324',
    projectId: 'codeara-apps',
    authDomain: 'codeara-apps.firebaseapp.com',
    storageBucket: 'codeara-apps.firebasestorage.app',
  );
}
